# note use "jeking3/release-feedback@v1" instead of "./" for production
# this example also helps me test changes
---
name: example
on:
  release:
    types:
      - published

env:
  SOME_DOCKER_IMAGE: some/thing:v.awesome

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Promote env to output
        id: promote
        run: echo "::set-output name=image::${SOME_DOCKER_IMAGE}"

      # add a markdown header
      # note: use jeking3/release-feedback@v1 instead of ./ in your files
      - uses: ./
        with:
          content: "### Build Status"
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # add a list entry
      # note: use jeking3/release-feedback@v1 instead of ./ in your files
      - uses: ./
        with:
          content: "- Beginning Build"
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # add multiple lines and a promoted environment variable
      # note: use jeking3/release-feedback@v1 instead of ./ in your files
      - uses: ./
        with:
          content: |-
            - Build Complete!
            - Fictitiously pushed to [${{ steps.promote.outputs.image }}](https://www.github.com/jeking3/release-feedback/packages)
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
